[project]
name = "rag-finance-kafka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "aiohttp>=3.12.15",
    "aiokafka>=0.12.0",
    "dotenv>=0.9.9",
    "jsonschema>=4.25.1",
]
